<?php
if (!defined('ABSPATH')) exit; // Exit if accessed directly

// You can use 1st or 2nd as well, just comment out the one You dont' want to use and uncomment the one You wish to use:

// 1. Less agnets, but mostly used agents, little less then bellow and faster processing time, This is default
$agents_to_check = array("Googlebot","Google","Yahoo","Amazon","Yandex","Facebook","Baidu","Bing","AhrefsBot","Pinterest","MJ12bot","Sogou","Go-http-client","Python","serpstatbot","ZoominfoBot","about.censys","Bytespider","PetalBot","DuckDuckBot","SeznamBot","SemrushBot","MojeekBot","OpenAI","Scrapy","Screaming Frog SEO Spider","OnCrawl","Glassdoor","Indeed","LinkedIn","Twitter","Instagram","YouTube","Vimeo","TikTok","Reddit","Quora","Stack Overflow","GitHub","GitLab","Slurp","Slackbot","Discordbot","archive.org","Barkrowler","CCBot","Daum","GrapeshotCrawler","ips-agent","Mail.RU_Bot","MSIECrawler","oBot","Sight","DotBot");

// 2.  More agents, but little bit slower proccessing time
// $agents_to_check = array("Google", "okhttp", "Yandex", "Facebook", "Amazon", "adsense", "Baidu", "Jakarta", "magpie", "Googlebot", "bing", "AhrefsBot", "Pinterest", "MJ12bot", "MegaIndex", "siteexplorer", "WBSearchBot", "sogou", "Go-http-client","Python","serpstatbot","domaincrawler","www.qwant.com","zoominfobot","Leikibot","hypefactors","Adsbot","babbar","python-httpx","about.censys","Edition developer","ThinkChaos","paloaltonetworks", "simplesite.com","Palo Alto Networks company","Nessus","Adbeat","Comscore","Bytespider","PetalBot","Bingbot","Yahoo","DuckDuckBot","Exabot","SeznamBot","Sogou Spider","Alexa Crawler","Majestic12","SemrushBot","MojeekBot","Qwantify","Nutch","Apache Tika","Diffbot","OpenAI","Octoparse","Scrapy","Beautiful Soup","Selenium","PhantomJS","Crawlbot","Wget","HTTrack","Teleport Pro","Netpeak Spider","Screaming Frog SEO Spider","Xenu Link Sleuth","DeepCrawl","Botify","OnCrawl","SE Ranking","Sitebulb","Link Explorer","WebMeUp","Linkpad","LinkMiner","LinkResearchTools","Monitor Backlinks","BuzzSumo","SimilarWeb","Owler","Crunchbase","G2","Glassdoor","Indeed","ZipRecruiter","SimplyHired","Monster","CareerBuilder","LinkedIn","Twitter","Instagram","YouTube","Vimeo","TikTok","Reddit","Quora","Stack Overflow","GitHub","Bitbucket","GitLab","Hacker News","Product Hunt","AngelList","Crunchbase Pro","PitchBook","CB Insights","Forbes","Bloomberg","Business Insider","Wall Street Journal","Financial Times","Reuters","Associated Press","CNN","BBC","Al Jazeera","NPR","The Guardian","The New York Times","The Washington Post","USA Today","Forbes Under 30","TechCrunch","VentureBeat","Wired","Mashable","Engadget","Gizmodo","CNET","PCMag","Digital Trends","The Verge","Recode","Slurp","FacebookExternalHit","Twitterbot","LinkedInBot","DotBot","Ezooms","Facebot","Mediapartners-Google","AdsBot-Google","BingPreview","Slackbot","Discordbot","80legs","Aboundex","AddThis","AlexaCrawler","AmorankSpider","AOLShield","AportWorm","archive.org_bot","Barkrowler","BLEXBot","BrandVerity","CCBot","Cliqzbot","Coccocbot","CompspyBot","Daum","DeuSu","DomainAppender","DTS_Agent","EasouSpider","ec2linkfinder","ExB Language Crawler","FatBot","Findxbot","Genieo","Gigabot","Go 1.1 package http","Goblin","grapeFX","GrapeshotCrawler","HaoSouSpider","heritrix","HuaweiSymantecSpider","ia_archiver","ICCrawler","Ichiro","iCjobs","igdeSpyder","IOI","ips-agent","iSiloX","James BOT","JennyBot","JobFeedBot","JS-Kit","JustView","Kraken","LeechCraft","Linkdex","Linkfluence","LinkpadBot","LinkTiger","LivelapBot","ltx71","LuminateBot","Luminati","lwp-request","Mail.RU_Bot","MSIECrawler","NetSeer","Nimbostratus-Bot","oBot","Ocelli","OpenLinkProfiler","OutclicksBot","PagesInventory","PaperLiBot","Pcore-HTTP","PiplBot","Pizilla","Ploetz+Zeller","RamBot","ScoutJet","Search-Preview","Seekport Crawler","semanticbot","SightMaxBot","SiteAnalyzer","SiteimproveBot","SiteSnagger","Slack-ImgProxy","Sight");
?>
